puntounicocontactov3_Production260124/Webpuc/Controllers/DirectorioController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Webpuc;

namespace pucultimate.Controllers
{
    [AllowAnonymous]
    public class DirectorioController: Controller
    {
        private readonly DbempleadosContext _empleado;

        public DirectorioController(DbempleadosContext empleado)
        {
            _empleado = empleado;
        }

        public async Task<IActionResult> DirectorioFIRCO() {

            var list_gerencia = await _empleado.ViewGerencia.OrderBy(x=>x.IdGerencia).
                AsNoTracking().
                ToListAsync();
            return View(list_gerencia);
        }

        //Procedimientos de busqueda
        [HttpPost]
        public async Task<JsonResult> LocateByPuesto(int idPuesto) {            
            var ResultadoXPuesto = await _empleado.ViewEmpleados.OrderBy(x => x.IdPuesto)
                .Where(x => x.IdPuesto == idPuesto && x.StatusEmpleado == 1)
                .AsNoTracking()
                .ToListAsync();
            return Json(ResultadoXPuesto);
        }

        [HttpPost]
        public async Task<JsonResult> LocateByRegex(string rgex) {
            List<int> ids = new List<int>();

            var metaBusqueda = await _empleado.ViewMetaEmpleados.Where(x => x.Metadata.Contains(rgex)).AsNoTracking().ToArrayAsync();
            
            foreach (var item in metaBusqueda)
            {
                ids.Add(item.NoEmpleado);
            }

            var ResultadoXRegex = from item in await _empleado.ViewEmpleados.AsNoTracking().ToArrayAsync()
                                  where ids.Contains(item.NoEmpleado)
                                  select item;

            return Json(ResultadoXRegex);
        }
    }
}

puntounicocontactov3_Production260124/Webpuc/ViewComponents/DirectorioPGViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Webpuc;
/*Directorio Personal Gerencias: Componente para mostrar al personal dependiendo de la gerencia estatal*/
namespace pucultimate.ViewComponents
{//DirectorioPersonalGerencia
    public class DirectorioPGViewComponent: ViewComponent
    {
        private readonly DbempleadosContext _empleados;
        public DirectorioPGViewComponent(DbempleadosContext empleados) {
            _empleados = empleados;
        }
        public async Task<IViewComponentResult> InvokeAsync(int idGerencia, int idDepartamento) {

            if (idDepartamento == 0)//Personal de Gerencias Estatales
            {
                var tablaEmpleados = await _empleados.ViewEmpleados.OrderBy(x => x.IdPuesto)
                                                                    .Where(x => x.IdGerencia == idGerencia && x.StatusEmpleado == 1)
                                                                    .AsNoTracking()
                                                                    .ToListAsync();
                return View(tablaEmpleados);
            }
            else { //Pesonal por departameto
                var tablaEmpleadosXArea = await _empleados.ViewEmpleados.OrderBy(x => x.IdPuesto)
                                                                    .Where(x => x.IdGerencia == idGerencia && x.IdDepartamento == idDepartamento && x.StatusEmpleado == 1)
                                                                    .AsNoTracking()
                                                                    .ToListAsync();
                return View(tablaEmpleadosXArea);
            }
        }
    }
}

puntounicocontactov3_Production260124/Webpuc/ViewComponents/DirectorioVOCViewComponent.cs
//Directorio mostrado por jerarquia para la vista
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Webpuc;

namespace pucultimate.ViewComponents
{//DirectorioVistaOficiansCentales
    public class DirectorioVOCViewComponent: ViewComponent
    {
        private readonly DbempleadosContext _contextDb;
        public DirectorioVOCViewComponent(DbempleadosContext contextDb)
        {
           _contextDb = contextDb;
        }

        public async Task<IViewComponentResult> InvokeAsync(int idDepartamento)
        {

            if (idDepartamento == 0)//Caso cuando es Direcciones
            {
                var direcciones = await _contextDb.Departamentos.Where(propa => propa.IdDepartamento == 100)
                                                                .AsNoTracking()
                                                                .ToListAsync();
                return View(direcciones);
            }
            else //Caso herencia de idDepartamento
            {
                //Si quitas el propa.GerenciaId == 9 automatiza para todas las gerencias la division por areas
                var subordinado = await _contextDb.Departamentos.Where(propa => propa.GerenciaId == 9 && propa.DepartamentoId == idDepartamento)
                                                                .AsNoTracking()
                                                                .ToListAsync();
                return View(subordinado);
            }
        }
    }
}

puntounicocontactov3_Production260124/Webpuc/ViewComponents/ListaPuestosViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using pucultimate;
using Webpuc;

namespace PuntoUnicoContacto.ViewComponents
{
    public class ListaPuestosViewComponent : ViewComponent
    {
        private readonly DbempleadosContext _puestos;

        public ListaPuestosViewComponent(DbempleadosContext puestos)
        {
            _puestos = puestos;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var lista = await _puestos.Puestos
                .AsNoTracking()
                .ToListAsync();
            return View(lista);
        }
    }
}

puntounicocontactov3_Production260124/Webpuc/Views/Directorio/DirectorioFIRCO.cshtml
@*
   Vista principal del Directorio
*@
@model IEnumerable<ViewGerencium>
@{
    ViewData["title"] = "Directorio";
}

<partial name="_navDirectorio"/>
@* Para el caso de Oficinas Centrales Esto es filtro dependiente por departamentos*@
@foreach (var item in Model.AsQueryable())
{
    if (item.IdGerencia == 9)
    {
        <div class="accordion accordion-flush" id="accordionFlushExample">
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-heading_@item.IdGerencia">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse_@item.IdGerencia" aria-expanded="false" aria-controls="flush-collapse_@item.IdGerencia">
                        OFICINAS CENTRALES
                    </button>
                </h2>
                <div id="flush-collapse_@item.IdGerencia" class="accordion-collapse collapse" aria-labelledby="flush-heading_@item.IdGerencia" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">
                        <div class="row">
                            <div class="col">
                                <strong>Direccion:</strong><span>@item.EntidadFederativa; @item.Localidad; @item.Municipio; @item.Calle; C.P. @item.CodigoPostal</span>
                            </div>
                            <div class="col">
                                <strong>Conmutador: </strong><span>@item.Conmutador</span>
                            </div>
                            <div class="col">
                                <strong>Marcación Rápida: </strong><span>@item.MarcRapida</span>
                            </div>
                        </div>
                        <div id="personal-table">
                            @* Para el caso de oficinas centrales se despliega el directorio por departementos *@
                            @await Component.InvokeAsync("DirectorioVOC",0)
                        </div>
                    </div>
                </div>
            </div>
        </div>
        break;
    }
}
@* <div class="accordion accordion-flush" id="accordionFlushExample">
    @await Component.InvokeAsync("DirectorioVOC",0)
</div> *@

 <div class="accordion accordion-flush" id="accordionFlushExample"> 
    @* Para el caso de las gerencias estatales *@
    @foreach (var item in Model.AsQueryable())
    {       
        if (item.IdGerencia != 9)
        {
            <div class="accordion-item" style="font-size:.8rem">
                <h2 class="accordion-header" id="flush-headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse_@item.IdGerencia" aria-expanded="false" aria-controls="flush-collapse_@item.IdGerencia">
                        @{

                            if (item.IdGerencia == 34)//Caso OIC
                            {
                                <span>ÓRGANO INTERNO DE CONTROL</span>
                            }
                            else if (item.IdGerencia == 33)// Caso comarca
                            {
                                <span>COMARCA LAGUNERA</span>
                            }
                            else
                            {
                                @item.EntidadFederativa.ToUpper()
                            }
                        }
                    </button>
                </h2>
                <div id="flush-collapse_@item.IdGerencia" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">
                        <div class="row">
                            <div class="col">
                                <strong>Direccion:</strong><span>@item.EntidadFederativa; @item.Localidad; @item.Municipio; @item.Calle; C.P. @item.CodigoPostal</span>
                            </div>
                            <div class="col">
                                <strong>Conmutador: </strong><span>@item.Conmutador</span>
                            </div>
                            <div class="col">
                                <strong>Marcación Rápida: </strong><span>@item.MarcRapida</span>
                            </div>
                        </div>
                        <div id="personal-table">
                            @* Para el caso de oficinas centrales se despliega el directorio por departementos *@
                            @await Component.InvokeAsync("DirectorioPG",new {idGerencia = item.IdGerencia, idDepartamento = 0} )
                        </div>
                    </div>
                </div>
            </div>
        }        
    }
</div>

@* Despliegue de la modal para los resultados buscados *@
<!-- Modal -->
<div class="modal fade" id="Modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">DIRECTORIO FIRCO | RESULTADO DE BUSQUEDA</h5>
                <button type="button" id="change-close-tik" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-content" id="ContenidoModal">
                <div>
                    <table id="tres-personal" class="table">
                        <thead>
                            <tr>
                                <th scope="col">Nombre</th>
                                <th scope="col">Puesto</th>
                                <th scope="col">Área</th>
                                <th scope="col">Correo</th>
                                <th scope="col">Ext.</th>
                            </tr>
                        </thead>
                        <tbody id="succeded-spersonal">
                            @* Aqui datos resultado *@
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" id="change-close-btn" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

@* Modal para notificaciones *@
<div class="modal fade" id="ModalNotificaciones" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content" id="ContenidoModalNotificaciones">
          @* Contenido dinamico en event-select *@  
        </div>
    </div>
</div>

puntounicocontactov3_Production260124/Webpuc/Views/Directorio/_navDirectorio.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor;
<div class="cintilla"></div>
<div class="row">
    <div class="col">
        <img src="http://apps.firco.gob.mx/icons/Logo-Secretaria-FIRCO.png" class="icon-banner" style="text-align:end;font-size:.8rem;" />
    </div>
</div>
<div class="row mt-1">
    <div class="col" style="text-align:center">
        <h3>FIDEICOMISO DE RIESGO COMPARTIDO</h3>
        <h4>DIRECTORIO TELEFÓNICO</h4>
    </div>
    <div class="col-3" style="text-align:end;font-size:.8rem;">
        <div><strong>Última Actualización: <sapan id="tipo-formato">31-08-2023</sapan></strong></div>
    </div>
</div>
<div class="col-md-12 row">
    <div class="col-md-6" style="align-items:center">
        @*<h6>Buscar: </h6>*@
        <div class="input-group mb-3">
            <input id="Dir-bus-rgx" type="text" class="form-control"
                   placeholder="Busqueda Rápida, ingresa palabras clave para encontrar coincidencias" />
            <button class="btn btn-outline-success" type="button" id="btn-busqueda-rgx">Buscar</button>
        </div>
    </div>
    <div class="col-md-6">
        @*  <h6>Búsqueda específica:</h6>*@
        @*Invocar componente*@
        @await Component.InvokeAsync("ListaPuestos")
    </div>
</div>
<div style="text-align:left">
    @* Despliega informacion si esta autenticado el usuario *@
    @if (HttpContextAccessor.HttpContext.User.Identity.IsAuthenticated)
    {
        <a class="btn btn-warning" asp-controller="Home" asp-action="MainApp">Regresa Menu</a>
    }else{
        <a class="btn btn-warning" asp-controller="Home" asp-action="Index">Regresa Home</a>
    }
</div>
@*<button id="RealizaPDF" onclick="HacePDF()" type="button" class="btn btn-success"> hacer pdf</button>*@
<br />
<div class="cintilla"></div>