puntounicocontactov3_Production260124/Webpuc/Controllers/AdminEmpleadoController.cs
using BuildDataFromDb.Interface;
using Templates;
using Message;
using Message.Formats;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MiscApp.Services;
using System.Security.Claims;

namespace Webpuc.Controllers
{
    [Authorize(Roles = "RPA_004")]//Solo acceso al Rol de personal 
    public class AdminEmpleadoController : Controller
    {
        private readonly DbempleadosContext _empleados;
        private readonly ICRUD<EmpleadoModel> updateservice;
        private readonly ICRUD<Empleado> empleadoDb;
        private readonly IMessageBuilder<MessageModel> messageBuilder;

        public AdminEmpleadoController(DbempleadosContext empleados, ICRUD<EmpleadoModel> updateservice, ICRUD<Empleado> empleadoDb,
            IMessageBuilder<MessageModel> messageBuilder) {
            _empleados = empleados;
            this.updateservice = updateservice;
            this.empleadoDb = empleadoDb;
            this.messageBuilder = messageBuilder;
        }

        //Vistas
        public IActionResult NotificSucceded() => View();
        public IActionResult NotificError() => View();
        public IActionResult InsertEmpleado() => View();
        public IActionResult UpdateEmp(int NoEmpleado) {
            //VAriables de sesion Claim
            var NombreDepartamento = HttpContext.User.FindFirst("Area").Value;
            var NombreDepartamentoSup = HttpContext.User.FindFirst("Direc").Value;
            ViewData["idEmpleado"] = NoEmpleado;

            HeaderViewModel header = new HeaderViewModel() {
                Institucion = "Fideicomiso de Riesgo Compartido",
                Direccion = NombreDepartamento,
                Gerencia = "",
                TipoF = "F-UDP",
                VersionF = "1.0"
            };
            
            return View(header);
        }

        //Respuestas json con javascript
        /*Envio de listas desde peticiones ajax*/
        [HttpPost]
        public async Task<JsonResult> ProcChangeArea(int idDep)
        { /*Filtrar por ubicacion, topado al estado al que pertence*/
            string nivel = "";

            var Areajson = await _empleados.Departamentos.Where(x => x.IdDepartamento == idDep)
                .AsNoTracking()
                .ToListAsync();
            //1.- Obtener el nivel del departamento
            foreach (var item in Areajson.AsQueryable())
            {
                nivel = item.NivelP;
            }

            //2.-Obtener el id del puesto respecto al nivel que corresponde al área:
            var Puestoespecifico = await _empleados.Puestos
                .FirstAsync(x => x.Nivel == nivel);

            //3.-Obtenermos el puesto a partir del nivel arrojado por el area
            var Puestosjson = await _empleados.Puestos
                .Where(x => x.IdPuesto >= Puestoespecifico.IdPuesto)
                .AsNoTracking()
                .ToListAsync();
            return Json(Puestosjson);
        }

        [HttpPost]
        public async Task<JsonResult> ProcChangeEntidadFederativa(int idEF)
        { /*Filtrar por ubicacion, topado al estado al que pertence*/
            var Areajson = await _empleados.Departamentos.Where(x => x.GerenciaId == idEF)
                .AsNoTracking()
                .ToListAsync();
            return Json(Areajson);
        }

        [HttpPost]
        public async Task<string> UpdateEmpleado(EmpleadoModel empleado)
        {
            //Historico del status actual del empleado
            EmpleadoModel empHistObject = null;
            var empleadohistoricoDb = _empleados.ViewEmpleados.Where(x => x.NoEmpleado == empleado.NoEmpleado)
                                    .AsNoTracking()
                                    .AsQueryable();
            foreach (var item in empleadohistoricoDb.AsQueryable())
            {
                empHistObject = new EmpleadoModel() { 
                    NoEmpleado = empleado.NoEmpleado,
                    FullName = item.Nombres + " " + item.ApellidoPaterno + " " + item.ApellidoMaterno,
                    State = item.EntidadFederativa,
                    DirDepartment = item.NombreDepartamento,
                    Job = item.Puesto,
                    Ext = item.Extension,
                    IsActive = (byte)item.StatusEmpleado
                };                
            }
            /*Actualizacion de los empleados en su ubicacion, area y puesto*/            
            //1.-Se realiza la actualizacion del empleado
            if (await updateservice.UpdateAsync(empleado)) 
            {
                UserIdentityModel empUpdated = null;
                //Establecer los datos del usuario logeado que esta realizando la operacion:
                UserIdentityModel usuarioSession = new UserIdentityModel() { 
                    FullName = HttpContext.User.Identity.Name,
                    Job = HttpContext.User.FindFirst("Puesto").Value,
                    DirDepartment = HttpContext.User.FindFirst("Area").Value,
                    Email = HttpContext.User.FindFirst(ClaimTypes.Email).Value,
                    Phone = HttpContext.User.FindFirst(ClaimTypes.OtherPhone).Value + "Ext." + HttpContext.User.FindFirst("Ext").Value
                };
                //Establecer la actualizacion del empleado
                var empleadoactualizado = _empleados.ViewEmpleados.Where(x => x.NoEmpleado == empleado.NoEmpleado)
                          .AsNoTracking()
                          .AsQueryable();
                foreach (var item in empleadoactualizado.AsQueryable())
                {
                    empUpdated = new UserIdentityModel()
                    {                     
                        State = item.EntidadFederativa,
                        DirDepartment = item.NombreDepartamento,
                        Job = item.Puesto,
                        Ext = item.Extension,
                        IsActive = (byte)item.StatusEmpleado
                    };
                }
                //Si se realizo la actualización enviar notificación:
                MessageNotifcService messageNotifcService = new MessageNotifcService(usuarioSession);//Establecer mensaje de body
                                                                                                     //Envio de correo
                MessageModel message = new MessageModel()
                {
                    To = new List<string> { "victor.rgarcia@firco.gob.mx" },
                    CCP = new List<string> { "soporte.tic@firco.gob.mx" },
                    Subject = "!ATENCION!, Actualizacion de Empleado",
                    BodyMessage = messageNotifcService.MsnUpdateEmpleado(empHistObject,empUpdated)
                };
                await messageBuilder.SendAsync(message);
                //Exito en en la actualizacion
                return "Se ha realizado la actualizacion";
            }
            return "Ocurrio un error";
        }

        //insertar elementos
        [HttpPost]
        public async Task<bool> InsertEmpleado(InsertEmpModel empleado) {

            //2.- Procedimiento para determinar un correo 

            GenerarCorreoService generarCorreoService = new GenerarCorreoService(_empleados);
            string correo = await generarCorreoService.GenerateEMail(empleado.Nombres, empleado.ApellidoPaterno, empleado.ApellidoMaterno);

            //3.- Procedimiento para insertar datos a la tabla Empleado
            Empleado empleadoDbobject = new Empleado(){ 
                NoEmpleado = empleado.NoEmpleado,
                Nombres = empleado.Nombres,
                ApellidoPaterno = empleado.ApellidoPaterno,
                ApellidoMaterno = empleado.ApellidoMaterno,
                Correo = correo.Trim(),
                Extension = empleado.Extension,
                StatusEmpleado = empleado.StatusEmpleado,
                Delegado = empleado.Delegado,
                Rfc = empleado.Rfc,
                Curp = empleado.Curp,
                DepartamentoId = empleado.DepartamentoId,
                PuestoId = empleado.PuestoId,
                TituloId = empleado.TituloId,
            };
            //Evaluar si se ha insertado un elemento a la tabla de Empleado
            if (await empleadoDb.InsertAsync(empleadoDbobject))
            {
                UserIdentityModel empUpdated = null;
                //Establecer los datos del usuario logeado que esta realizando la operacion:
                UserIdentityModel usuarioSession = new UserIdentityModel()
                {
                    FullName = HttpContext.User.Identity.Name,
                    Job = HttpContext.User.FindFirst("Puesto").Value,
                    DirDepartment = HttpContext.User.FindFirst("Area").Value,
                    Email = HttpContext.User.FindFirst(ClaimTypes.Email).Value,
                    Phone = HttpContext.User.FindFirst(ClaimTypes.OtherPhone).Value + "Ext." + HttpContext.User.FindFirst("Ext").Value
                };
                //Si se realizo la actualización enviar notificación:
                MessageNotifcService messageNotifcService = new MessageNotifcService(usuarioSession);//Establecer mensaje de body
                                                                                                     //Envio de correo
                MessageModel message = new MessageModel()
                {
                    To = new List<string> { "victor.rgarcia@firco.gob.mx" },
                    CCP = new List<string> { "soporte.tic@firco.gob.mx" },
                    Subject = "!ATENCION!, Actualizacion de Empleado",
                    BodyMessage = messageNotifcService.MsnInsertEmpleado(empleadoDbobject)
                };
                await messageBuilder.SendAsync(message);
                //Notificacion general de exito en la operacion de la base de datos
                return true;
            }
            //Notificacion general en el error general 

puntounicocontactov3_Production260124/Webpuc/Controllers/DirectorioController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Webpuc;

namespace pucultimate.Controllers
{
    [AllowAnonymous]
    public class DirectorioController: Controller
    {
        private readonly DbempleadosContext _empleado;

        public DirectorioController(DbempleadosContext empleado)
        {
            _empleado = empleado;
        }

        public async Task<IActionResult> DirectorioFIRCO() {

            var list_gerencia = await _empleado.ViewGerencia.OrderBy(x=>x.IdGerencia).
                AsNoTracking().
                ToListAsync();
            return View(list_gerencia);
        }

        //Procedimientos de busqueda
        [HttpPost]
        public async Task<JsonResult> LocateByPuesto(int idPuesto) {            
            var ResultadoXPuesto = await _empleado.ViewEmpleados.OrderBy(x => x.IdPuesto)
                .Where(x => x.IdPuesto == idPuesto && x.StatusEmpleado == 1)
                .AsNoTracking()
                .ToListAsync();
            return Json(ResultadoXPuesto);
        }

        [HttpPost]
        public async Task<JsonResult> LocateByRegex(string rgex) {
            List<int> ids = new List<int>();

            var metaBusqueda = await _empleado.ViewMetaEmpleados.Where(x => x.Metadata.Contains(rgex)).AsNoTracking().ToArrayAsync();
            
            foreach (var item in metaBusqueda)
            {
                ids.Add(item.NoEmpleado);
            }

            var ResultadoXRegex = from item in await _empleado.ViewEmpleados.AsNoTracking().ToArrayAsync()
                                  where ids.Contains(item.NoEmpleado)
                                  select item;

            return Json(ResultadoXRegex);
        }
    }
}

puntounicocontactov3_Production260124/Webpuc/ViewComponents/FormInsertEmpViewComponent.cs
using Templates;
using Microsoft.AspNetCore.Mvc;
using MiscApp.Interface;

namespace Webpuc.ViewComponents
{
    public class FormInsertEmpViewComponent: ViewComponent
    {
        private readonly ICatalogosdb<LCatalogosModel> catalogosdb;

        public FormInsertEmpViewComponent(ICatalogosdb<LCatalogosModel> catalogosdb)
        {
            this.catalogosdb = catalogosdb;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var catalogos = await catalogosdb.GetCatalogoEmpleadosDb();

            return View(catalogos);
        }
    }
}

puntounicocontactov3_Production260124/Webpuc/ViewComponents/FormatsHeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Templates;

namespace Webpuc.ViewComponents
{
    public class FormatsHeaderViewComponent : ViewComponent
    {
        //Definir la cabecer 
        public Task<IViewComponentResult> InvokeAsync(HeaderViewModel headerViewModel) {

            return Task.FromResult<IViewComponentResult>(View(headerViewModel));
        }
    }
}

puntounicocontactov3_Production260124/Webpuc/ViewComponents/UpdateEmpViewComponent.cs
using BuildDataFromDb.Interface;
using Templates;
using Microsoft.AspNetCore.Mvc;
using MiscApp.Interface;

namespace Webpuc.ViewComponents
{
    public class UpdateEmpViewComponent : ViewComponent
    {
        private readonly ICRUD<UserIdentityModel> usuario;
        private readonly ICatalogosdb<LCatalogosModel> catalogosdb;

        public UpdateEmpViewComponent(ICRUD<UserIdentityModel> usuario, ICatalogosdb<LCatalogosModel> catalogosdb)
        {
            this.usuario = usuario;
            this.catalogosdb = catalogosdb;
        }

        public async Task<IViewComponentResult> InvokeAsync(int id) {//Se recibe el numero de empleado  
            
            //Objeto para la vista requisitos de actualizacion de empleado
            UpdateEmpModel updateEmpModel = new UpdateEmpModel() { 
                UserIdentity = await usuario.SelectAsync(id),
                lCatalogosModels = await catalogosdb.GetCatalogoEmpleadosDb(id)
            };

            return View(updateEmpModel);
        }



    }
}

puntounicocontactov3_Production260124/Webpuc/Views/AdminEmpleado/InsertEmpleado.cshtml
@*
    Formulario para agregar a un empleado
*@
@{
    ViewData["title"] = "AddEmp";
}
<partial name="_MenuPrincipal" />
<partial name="_FichaUsuario" />
<div id="msn-alert-adminEmp"></div>
@* Aqui el encabezado *@
<div style="background: #b38e5d;height: 0.5rem;"></div>
@await Component.InvokeAsync("FormatsHeader",new HeaderViewModel{Institucion="Fideicomiso de Riesgo Compartido",
                                                                    Direccion="DEAF",
                                                                    Gerencia="Subgerencia Personal",
                                                                    TipoF="I-FPUC",
                                                                    VersionF="1.0"})

<div style="background: white;height: 0.5rem;"></div>
@await Component.InvokeAsync("FormInsertEmp")

puntounicocontactov3_Production260124/Webpuc/Views/AdminEmpleado/NotificError.cshtml
@*
    Notificacion de operacion exitosa
*@
@{
    ViewData["titlw"] = "Exito";
}

<div style="font-family: 'Montserrat';margin: auto; width: 60%; margin-top: 5rem;">
    <div style="background: red;height: 0.5rem;"></div>
    <div style="background-color: #F6F6F6;font-family: 'Montserrat';text-align: justify; padding: 2rem; height: 30rem;">
        <div style="margin: auto;margin-top: 2rem; width: 40%;text-align: center;">
            <img src="http://apps.firco.gob.mx/icons/error-icon.png" width="55%/>
        </div>
        <div style="text-align: center;">
            <h3>¡ATENCIÓN! OCURRION UN ERROR EN LA OPERACION, VERIFIQUE QUE EL NÚMERO DE EMPLEADO NO EXISTA</h3>
        </div>
        <div>
            <a class="btn btn-warning" style="width: 80%" asp-action="MainApp" asp-controller="Home">REGRESAR</a>
        </div>
    </div>
    <div style="background: red;width: 100%;height: 0.5rem;"></div>
</div>  

puntounicocontactov3_Production260124/Webpuc/Views/AdminEmpleado/NotificSucceded.cshtml
@*
    Notificacion de operacion exitosa
*@
@{
    ViewData["titlw"] = "Exito";
}
<div style="font-family: 'Montserrat';margin: auto; width: 60%; margin-top: 5rem;">
    <div style="background: #98a088;height: 0.5rem;"></div>
    <div style="background-color: #F6F6F6;font-family: 'Montserrat';text-align: justify; padding: 2rem; height: 30rem;">
        <div style="margin: auto;margin-top: 2rem; width: 40%;text-align: center;">
            <img src="http://apps.firco.gob.mx/icons/succeded-icon.png" width="55%"/>
        </div>
        <div style="text-align: center;">
            <h1>¡OPERACION EXITOSA!</h1>
        </div>
        <div>
            <a class="btn btn-warning" style="width: 80%" asp-action="MainApp" asp-controller="Home">REGRESAR</a>
        </div>
    </div>
    <div style="background: #98a088;width: 100%;height: 0.5rem;"></div>
</div>

puntounicocontactov3_Production260124/Webpuc/Views/AdminEmpleado/UpdateEmp.cshtml
@*
    Actualizacion de un empleado
*@
@model HeaderViewModel
@{
    ViewData["title"] = "AdminApp";
}
<partial name="_MenuPrincipal" />
<partial name="_FichaUsuario" />
<div id="msn-alert-adminEmp"></div>
@* <div style="font-family: 'Montserrat';margin: auto; width: 70%"> *@

    @* Aqui el encabezado *@
    <div style="background: #b38e5d;height: 0.5rem;"></div>
    @await Component.InvokeAsync("FormatsHeader",new HeaderViewModel{Institucion="Fideicomiso de Riesgo Compartido",
                                                                    Direccion=Model.Direccion,
                                                                    Gerencia=Model.Gerencia,
                                                                    TipoF=Model.TipoF,
                                                                    VersionF=Model.VersionF})
    <div style="background: white;height: 0.5rem;"></div>
    @await Component.InvokeAsync("UpdateEmp",ViewData["idEmpleado"])
    <div style="background: white;height: 0.5rem;"></div>
    <div class="mt-2 mb-2">
        <button id="btn-sc-admemp" type="button" class="btn btn-success">Guardar</button>
        <a class="btn btn-danger" asp-action="DirectorioFIRCO" asp-controller="Directorio">Cancelar</a>
    </div>
@* </div> *@

@* Modal de notificaciones *@
<div class="modal fade" id="Modal-adminEmp" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">NOTIFICACIÓN DE ACTUALIZACIÓN</h5>
            </div>
            <div class="modal-content" id="ContenidoModal">
               <div id="notific-modal-adminEmp" class="alert alert-success">
                   
               </div>
            </div>
            <div class="modal-footer">
                <a asp-action="MainApp" asp-controller="Home" class="btn btn-warning">Cerrar</a>
            </div>
        </div>
    </div>
</div>