puntounicocontactov3_Production260124/Webpuc/Controllers/ERISCController.cs
using Microsoft.AspNetCore.Mvc;

namespace Webpuc.Controllers
{
    //Equipo de Respuestas ante Incidentes de Seguridad de la Informacion
    public class ERISCController : Controller
    {
        public IActionResult HomeERISC() => View();
    }
}

puntounicocontactov3_Production260124/Webpuc/ViewComponents/ModuleAccessViewComponent.cs
using BuildDataFromDb.Interface;
using Templates;
using Microsoft.AspNetCore.Mvc;

namespace Webpuc.ViewComponents
{
    //Definir el acceso a los modulos de nuestra aplicaciones dependiendo del la autorizacion por perfiles  y modulos de la base de datos
    public class ModuleAccessViewComponent : ViewComponent
    {
        private readonly ICRUD<List<ModulosPerfilModel>> accesoModulos;

        //Programar 
        public ModuleAccessViewComponent(ICRUD<List<ModulosPerfilModel>> accesoModulos)
        {
            this.accesoModulos = accesoModulos;
        }

        public async Task<IViewComponentResult> InvokeAsync(int id)
        {
            var catalogo = await accesoModulos.SelectAsync(id);

            return View(catalogo);
        }
    }
}

puntounicocontactov3_Production260124/Webpuc/Views/ERISC/HomeERISC.cshtml
@*
    Menu principal para el Equipo de Respuesta ante Incidentes de Seguridad de la Informacion
*@
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor;
@{
    ViewData["title"] = "ERISC";
}
<div class="alert alert-info text-center">Equipo de Respuesta ante Incidentes de Seguirdad de la Información</div>
<partial name="_MenuPrincipal" />
<partial name="_FichaUsuario" />
@await Component.InvokeAsync("ModuleAccess",
                            Int32.Parse(HttpContextAccessor.HttpContext.User.FindFirst("Id").Value.ToString()))